version: '3'
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
  helloworld:
    image: strm/helloworld-http
    ports:
      - "80:80"
  postgres:
    container_name: hello-postgres
    image: postgres 
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
