version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ..:/workspace:cached
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    #   - ${HOME}/.Xauthority:/root/.Xauthority
    # environment:
    #   - DISPLAY=${DISPLAY}