FROM mcr.microsoft.com/playwright:v1.35.0-jammy
RUN apt-get update && apt-get install -y x11-apps iproute2 weston
#FROM ubuntu:23.04
#RUN apt-get update && apt-get install -y x11-apps wayland-utils iproute2 weston
